language: ruby
rvm:
  - 2.6.6
cache:
  bundler: true
  yarn: true
services:
  - redis-server
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
addons:
  postgresql: '12.2'
before_script:
  - psql -c 'create database water_your_plants_test;' -U postgres
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - SECRET_KEY_BASE=a RAILS_ENV=production bundle exec rake assets:precompile
  - bundle exec rake test
  - bundle exec rake test:system
deploy:
  provider: heroku
  api_key:
    secure: ENV["HEROKU-TOKEN"]
