language: ruby
rvm:
  - 2.6.6
cache:
  bundler: true
  yarn: true
services:
  - postgresql
  - elasticsearch
  - redis-server
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
addons:
  postgresql: '12.2'
before_script:
  - sleep 10
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: ENV["HEROKU-TOKEN"]
