version: '3.3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis

  sidekiq:
    build: .
    depends_on:
      - app
      - db
      - redis
    volumes:
      - .:/app
    environment:
      POSTGRES_PASSWORD: password
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec sidekiq"

  webpack-dev-server:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - '3035:3035'
    environment:
      - "NODE_ENV:development"
      - "RAILS_ENV_development"
      - "WEBPACKER_DEV_SERVER_HOST=0.0.0.0"

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpack-dev-server
      - redis
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack-dev-server
      PG_PASSWORD: password
    #entrypoint: ./entrypoints/docker-entrypoint.sh

