version: '3.3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    ports:
      - 6379:6379

  sidekiq:
    image: jasminj000/water_your_plants:latest
    depends_on:
      - app
      - db
      - redis
    volumes:
      - .:/app
    environment:
      POSTGRES_PASSWORD: password
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

  webpack-dev-server:
    image: jasminj000/water_your_plants:latest
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - 3035:3035
    environment:
      - "NODE_ENV:development"
      - "RAILS_ENV_development"
      - "WEBPACKER_DEV_SERVER_HOST=0.0.0.0"

  app:
    image: jasminj000/water_your_plants:latest
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - webpack-dev-server
      - redis
    entrypoint: ./entrypoints/docker-entrypoint.sh
    container_name: water_your_plants_app_1
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack-dev-server
      PG_PASSWORD: password

