version: '3.3'
services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:6.0.6-alpine
    ports:
      - 6379:6379

  sidekiq:
    build: .
    depends_on:
      - app
      - db
      - redis
    volumes:
      - .:/app:cached
    environment:
      POSTGRES_PASSWORD: password
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

  webpack-dev-server:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app:cached
    ports:
      - 3035:3035
    environment:
      - "NODE_ENV:development"
      - "RAILS_ENV_development"
      - "WEBPACKER_DEV_SERVER_HOST=0.0.0.0"

  app:
    build: .
    volumes:
      - .:/app:cached
    ports:
      - 3000:3000
    depends_on:
      - db
      - webpack-dev-server
      - redis
    entrypoint: ./entrypoints/docker-entrypoint.sh
    container_name: water_your_plants_app_1
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack-dev-server
      PG_PASSWORD: password

