version: '3.3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  webpack:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - '3035:3035'
    environment:
      - "NODE_ENV:development"
      - "RAILS_ENV_development"
      - "WEBPACKER_DEV_SERVER_HOST=0.0.0.0"

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpack
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack
      PG_PASSWORD: password
