fertilize_notification_job:
  cron: "0 10 * * *" #every day at 1 pm
  class: "FertilizeNotificationJob"

water_notification_job:
  cron: " 11 * * *" #every day at 1 pm
  class: "WaterNotificationJob"
