fertilize_notification_job:
  cron: "0 14 * * *" #every day at 1 pm
  class: "FertilizeNotificationJob"

water_notification_job:
  cron: "0 15 * * *" #every day at 1 pm
  class: "WaterNotificationJob"
