fertilize_notification_job:
  cron: "*/1 * * * *" #every day at 1 pm
  class: "FertilizeNotificationJob"

water_notification_job:
  cron: "*/1 * * * *" #every day at 1 pm
  class: "WaterNotificationJob"
